[package]
name = "file_buffer_size_test"
version = "0.1.0"
authors = ["garyemerson <gmohammadioun@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.7.3"
